import {CodeIcon} from '@sanity/icons/Code'
import {defineField, defineType} from 'sanity'

export const labPage = defineType({
  name: 'labPage',
  title: 'Lab page',
  type: 'document',
  icon: CodeIcon,
  groups: [
    {name: 'hero', title: 'Hero', default: true},
    {name: 'archive', title: 'Archive'},
    {name: 'closing', title: 'Closing'},
    {name: 'seo', title: 'SEO'},
  ],
  fields: [
    defineField({
      name: 'eyebrow',
      title: 'Eyebrow',
      type: 'string',
      group: 'hero',
      initialValue: 'LAB ARCHIVE // EXPERIMENTS IN INTERACTION & CREATIVE CODE',
      validation: (rule) => rule.required().max(100),
    }),
    defineField({
      name: 'heading',
      title: 'Heading',
      type: 'string',
      group: 'hero',
      initialValue: 'Things I build when I’m curious.',
      validation: (rule) => rule.required().max(90),
    }),
    defineField({
      name: 'introduction',
      title: 'Introduction',
      type: 'text',
      rows: 3,
      group: 'hero',
      initialValue:
        'Small experiments in interaction, tactile interfaces, real-time data visualisation, and creative frontend development.',
      validation: (rule) => rule.required().max(280),
    }),
    defineField({
      name: 'activeStudiesLabel',
      title: 'Active studies label',
      type: 'string',
      group: 'hero',
      initialValue: 'Active studies',
      validation: (rule) => rule.required().max(40),
    }),
    defineField({
      name: 'surpriseLabel',
      title: 'Random experiment button',
      type: 'string',
      group: 'hero',
      initialValue: 'Surprise me',
      validation: (rule) => rule.required().max(40),
    }),
    defineField({
      name: 'archiveEyebrow',
      title: 'Archive eyebrow',
      type: 'string',
      group: 'archive',
      initialValue: 'Notebook index',
      validation: (rule) => rule.required().max(50),
    }),
    defineField({
      name: 'archiveHeading',
      title: 'Archive heading',
      type: 'string',
      group: 'archive',
      initialValue: 'Earlier explorations & micro-tools',
      validation: (rule) => rule.required().max(90),
    }),
    defineField({
      name: 'archiveNote',
      title: 'Archive note',
      type: 'string',
      group: 'archive',
      initialValue: 'Curated selection',
      validation: (rule) => rule.max(80),
    }),
    defineField({
      name: 'closingEyebrow',
      title: 'Closing eyebrow',
      type: 'string',
      group: 'closing',
      initialValue: 'Status: exploratory',
      validation: (rule) => rule.required().max(50),
    }),
    defineField({
      name: 'closingHeading',
      title: 'Closing heading',
      type: 'string',
      group: 'closing',
      initialValue: 'Still experimenting.',
      validation: (rule) => rule.required().max(70),
    }),
    defineField({
      name: 'closingMessage',
      title: 'Closing message',
      type: 'text',
      rows: 3,
      group: 'closing',
      initialValue: 'New things appear here as I learn, break things, and explore the medium.',
      validation: (rule) => rule.required().max(220),
    }),
    defineField({
      name: 'workLinkLabel',
      title: 'Work link label',
      type: 'string',
      group: 'closing',
      initialValue: 'View work',
      validation: (rule) => rule.required().max(40),
    }),
    defineField({
      name: 'githubLinkLabel',
      title: 'GitHub link label',
      type: 'string',
      group: 'closing',
      initialValue: 'GitHub',
      validation: (rule) => rule.required().max(40),
    }),
    defineField({
      name: 'contactLinkLabel',
      title: 'Contact link label',
      type: 'string',
      group: 'closing',
      initialValue: 'Contact',
      validation: (rule) => rule.required().max(40),
    }),
    defineField({
      name: 'seo',
      title: 'SEO and social sharing',
      type: 'seoMetadata',
      group: 'seo',
    }),
  ],
  preview: {
    prepare: () => ({title: 'Lab page', subtitle: 'Editorial copy, archive labels and SEO'}),
  },
})
